image: fedora:29

stages:
  - build
  - deploy

before_script:
  - dnf install -y gcc ccache gettext gtk-doc meson ninja-build redhat-rpm-config
  - dnf install -y glib2-devel glib2-doc clutter-devel clutter-doc gtk3-devel gtk3-doc clutter-gtk-devel clutter-gtk-doc cairo-devel cairo-doc sqlite-devel libsoup-devel gobject-introspection-devel

.ccache-setup: &ccache-setup
  variables:
    CCACHE_BASEDIR: "${PWD}"
    CCACHE_DIR: "${CCACHE_BASEDIR}/_ccache"

build-champlain:
  stage: build
  script:
    - mkdir -p _ccache
    - ccache --zero-stats
    - ccache --show-stats
    - meson -Dwidgetry=true -Ddemos=true -Dgtk_doc=true _build .
    - ninja -C _build
    - ninja -C _build test
    - ninja -C _build champlain-doc
    - ninja -C _build champlain-gtk-doc
    - ccache --show-stats
  artifacts:
    name: "champlain-doc"
    paths:
      - _build/docs/reference/html
      - _build/docs/reference-gtk/html
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - _ccache/
  <<: *ccache-setup

pages:
  stage: deploy
  dependencies:
    - build-champlain
  script:
    - mkdir -p public/
    - mv _build/docs/reference/html/ public/champlain/
    - mv _build/docs/reference-gtk/html/ public/champlain-gtk/
  artifacts:
    paths:
      - public
  only:
    - master
